package net.sxkeji.xddistance;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import net.sxkeji.xddistance.PictureInfo;

import net.sxkeji.xddistance.PictureInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig pictureInfoDaoConfig;

    private final PictureInfoDao pictureInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        pictureInfoDaoConfig = daoConfigMap.get(PictureInfoDao.class).clone();
        pictureInfoDaoConfig.initIdentityScope(type);

        pictureInfoDao = new PictureInfoDao(pictureInfoDaoConfig, this);

        registerDao(PictureInfo.class, pictureInfoDao);
    }
    
    public void clear() {
        pictureInfoDaoConfig.getIdentityScope().clear();
    }

    public PictureInfoDao getPictureInfoDao() {
        return pictureInfoDao;
    }

}
